{% set name = "cryptocode" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryptocode-{{ version }}.tar.gz
  sha256: 1cf6718e542981ceafc1000b00d60458f8620a1e5adfceb3fc297205b38774cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pycryptodomex

test:
  imports:
    - cryptocode
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gdavid7/cryptocode
  summary: Python library used to encrypt and decrypt strings in the simplest possible way.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
